### ISSUE TITLE
Query timeframe

### ISSUE THREAD

**Issue by lambdaschmied2** [lambdaschmiede/freitag#3]
In some cases we need to query a time-frame to get all of the holidays for multiple months and years.

Currently we would have to call the query function multiple times for each month we are interested in in our time-frame.

**Comment by javahippie** [comment]
Would it be sufficient to allow for the querying of multiple years, e.g. 2021, 2022, or do we need a "from... to..." ?

**Comment by lambdaschmied2** [comment]
Both could work. Yet, for my current purpose the "from" and "to" would mean less transformation on my side and a more understandable code IMO.

**Comment by javahippie** [comment]
@lambdaschmied2  Added the proposed changes to 0.1.4-SNAPSHOT, can you confirm this works as intended?

https://clojars.org/com.lambdaschmiede/freitag/versions/0.1.4-SNAPSHOT

See the new API at the usage paragraph of the README.md, changelog here: https://github.com/lambdaschmiede/freitag/blob/master/CHANGELOG.md

**Comment by lambdaschmied2** [comment]
Works as intended for me.
